le_domain: "vpn.clientb.senthilreddy.com"
le_email: "admin@senthilreddy.com"

ovpn_users:
  - alice
  - bob

ovpn_ssm_prefix: "/client-b/openvpn/clients"
ovpn_ssm_kms_key_id: "alias/ssm-sshs"
ovpn_ssm_tier: "Standard"
ovpn_ssm_param_tags:
  Project: "client-b"
  Component: "openvpn"
